---
fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: v9.7.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
      ref: v9.0.2
  symlinks:
    sysfs: "#{source_dir}"
