---
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - spec/fixtures/**/*
    - pkg/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/LineLength:
  Max: 140

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: single_quotes
